In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

TensorFlow 2.x selected.


In [5]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [0]:
df = pd.read_csv('/content/sample_data/weatherAUS.csv', sep =',')

In [9]:
df.head()

Date Location  MinTemp  ...  RainToday  RISK_MM  RainTomorrow
0  2008-12-01   Albury     13.4  ...         No      0.0            No
1  2008-12-02   Albury      7.4  ...         No      0.0            No
2  2008-12-03   Albury     12.9  ...         No      0.0            No
3  2008-12-04   Albury      9.2  ...         No      1.0            No
4  2008-12-05   Albury     17.5  ...         No      0.2            No

[5 rows x 24 columns]

In [10]:
df.shape

(142193, 24)

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null obje

In [37]:
df.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [0]:
df_na = df.drop(columns = ['Sunshine','Evaporation','Cloud3pm','Cloud9am','Date', 'Location', 'RISK_MM'], axis = 1)

In [39]:
df_na.shape

(142193, 17)

In [40]:
df_na.isnull().sum()

MinTemp            637
MaxTemp            322
Rainfall          1406
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow         0
dtype: int64

In [41]:
df_na.shape

(142193, 17)

In [0]:
df_na_num = df_na.replace({'No':0, 'Yes':1})

In [0]:
df_reduced_2 = df_na_num.drop(['WindGustDir','WindDir9am', 'WindDir3pm'], axis=1)

In [0]:
#Tirando os Valores Nulos
df_reduced_2 = df_na_num.dropna(axis = 0)

In [47]:
df_na_num.shape

(112925, 17)

In [21]:
#Troca os valores das colunas que não são numericos
#cat = ['WindGustDir', 'WindDir9am', 'WindDir3pm']
#df_na_num = pd.get_dummies(df_na_num,columns=cat, drop_first=True)
#df_na_num.shape

(112925, 59)

In [0]:
Y = df_na_num.RainTomorrow
X = df_na_num.drop(['RainTomorrow'], axis = 1)

In [34]:
from sklearn import preprocessing # To get MinMax Scaler function

#Normalizando a entrada
min_max_scaler = preprocessing.MinMaxScaler()

X_norm = pd.DataFrame( min_max_scaler.fit_transform(X) , columns = X.columns)


from sklearn.metrics import accuracy_score # To calculate the score
from sklearn.feature_selection import SelectKBest # Univariate Feature Selection
from sklearn.feature_selection import chi2 # To apply Univariate Feature Selection
# Initialize SelectKBest function
UnivariateFeatureSelection = SelectKBest(chi2, k=13).fit(X_norm, Y)



# Cria a lista para exibição
diccionario = {key:value for (key, value) in zip(UnivariateFeatureSelection.scores_, X_norm.columns)}
sorted(diccionario.items())



[(0.3255294820099362, 'WindGustDir_S'),
 (0.8582959565864693, 'WindDir3pm_WSW'),
 (0.954218568984879, 'WindGustDir_SSW'),
 (1.1082687135086138, 'WindDir3pm_SSW'),
 (1.7407292706643156, 'WindDir9am_SW'),
 (4.099651540795119, 'WindDir9am_NE'),
 (5.589836261441262, 'WindDir3pm_S'),
 (5.656013627261231, 'WindDir9am_SSW'),
 (6.413638989706271, 'Temp9am'),
 (9.4934594953953, 'WindGustDir_WSW'),
 (9.66609943286879, 'WindGustDir_NNE'),
 (14.195610955938822, 'WindDir9am_WSW'),
 (20.907900525823955, 'WindGustDir_SW'),
 (30.858622980811553, 'WindDir3pm_NNE'),
 (31.136992889521608, 'MinTemp'),
 (34.72020095635405, 'WindDir3pm_NE'),
 (35.71214264301845, 'WindGustDir_SSE'),
 (40.52633614152493, 'WindDir9am_S'),
 (44.943814421136395, 'WindDir3pm_SSE'),
 (48.95487501328169, 'WindGustDir_NE'),
 (51.76858067354694, 'WindGustDir_SE'),
 (51.80212325364714, 'WindSpeed3pm'),
 (53.67424940291009, 'WindDir3pm_SW'),
 (54.76393558339518, 'WindDir9am_WNW'),
 (60.12613671542411, 'WindDir3pm_W'),
 (60.931309921861

In [48]:
X_top4 = X_norm[['RainToday', 'Humidity3pm','Rainfall','Humidity9am']]
X_top4.head()

RainToday  Humidity3pm  Rainfall  Humidity9am
0        0.0         0.22  0.001632         0.71
1        0.0         0.25  0.000000         0.44
2        0.0         0.30  0.000000         0.38
3        0.0         0.16  0.000000         0.45
4        0.0         0.33  0.002720         0.82

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test_val,y_train,y_test_val = train_test_split(X_top4,Y,test_size = 0.4,random_state = 40)
x_test, x_val, y_test, y_val = train_test_split(x_test_val,y_test_val,test_size = 0.5,random_state = 40)

In [62]:
X.shape

(112925, 58)

In [63]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,Sequential
tf.keras.__version__

'2.2.4-tf'

In [0]:
model = Sequential ([
    layers.Dense(5, activation ='relu', input_dim= 4),
    # layers.Dense(30, activation ='relu'),
    layers.Dense(1, activation ='sigmoid'),    
])

In [0]:
# model.compile (optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy']) #0,8467
model.compile (optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #0,8336

In [72]:
model.fit(x_train.values, y_train.values, epochs = 10, batch_size = 100)

Train on 67755 samples
Epoch 1/10
67755/67755 [==============================] - 1s 21us/sample - loss: 0.5164 - accuracy: 0.7813
Epoch 2/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.4265 - accuracy: 0.8182
Epoch 3/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.4016 - accuracy: 0.8340
Epoch 4/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.3989 - accuracy: 0.8356
Epoch 5/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.3983 - accuracy: 0.8361
Epoch 6/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.3982 - accuracy: 0.8359
Epoch 7/10
67755/67755 [==============================] - 1s 15us/sample - loss: 0.3980 - accuracy: 0.8356
Epoch 8/10
67755/67755 [==============================] - 1s 14us/sample - loss: 0.3976 - accuracy: 0.8362
Epoch 9/10
67755/67755 [==============================] - 1s 14us/sample - loss: 0.3971 - accuracy: 0.8359
Epoch 10/10
67

In [73]:
results = model.evaluate(x_test.values, y_test.values)
results

22585/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.40187213499117985, 0.8351561]

In [74]:
y_pred_test = model.predict(x_test.values)

y_pred_test = (y_pred_test>0.5)
y_pred_test

array([[False],
       [False],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [75]:
y_test.values

array([0, 0, 1, ..., 1, 0, 0])

In [76]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

confusion_matrix(y_test.values, y_pred_test)

array([[16654,   858],
       [ 2865,  2208]])

In [77]:
X_top9 = X_norm[['RainToday', 'Humidity3pm', 'Rainfall', 'Humidity9am', 'WindGustSpeed', 'Temp3pm', 'Pressure9am', 'MaxTemp', 'Pressure3pm']]
X_top9.head()
x_train,x_test_val,y_train,y_test_val = train_test_split(X_top9,Y,test_size = 0.4,random_state = 40)
x_test, x_val, y_test, y_val = train_test_split(x_test_val,y_test_val,test_size = 0.5,random_state = 40)
model_top9 = Sequential( [
layers.Dense(10, activation='relu', input_dim=9),
layers.Dense(10, activation='relu'),
layers.Dense(1,activation='sigmoid')] )
model_top9.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model_top9.fit( x_train.values, y_train.values, epochs=10, batch_size=100 )
results = model_top9.evaluate(x_test.values, y_test.values)
results

Train on 67755 samples
Epoch 1/10
67755/67755 [==============================] - 2s 24us/sample - loss: 0.4234 - accuracy: 0.8110
Epoch 2/10
67755/67755 [==============================] - 1s 18us/sample - loss: 0.3687 - accuracy: 0.8421
Epoch 3/10
67755/67755 [==============================] - 1s 18us/sample - loss: 0.3653 - accuracy: 0.8430
Epoch 4/10
67755/67755 [==============================] - 1s 19us/sample - loss: 0.3632 - accuracy: 0.8445
Epoch 5/10
67755/67755 [==============================] - 1s 19us/sample - loss: 0.3620 - accuracy: 0.8447
Epoch 6/10
67755/67755 [==============================] - 1s 19us/sample - loss: 0.3595 - accuracy: 0.8459
Epoch 7/10
67755/67755 [==============================] - 1s 18us/sample - loss: 0.3581 - accuracy: 0.8460
Epoch 8/10
67755/67755 [==============================] - 1s 18us/sample - loss: 0.3577 - accuracy: 0.8464
Epoch 9/10
67755/67755 [==============================] - 1s 18us/sample - loss: 0.3569 - accuracy: 0.8456
Epoch 10/10
67

[0.35929641077047114, 0.846801]

In [0]:
model.save('/content/drive/My Drive/Colab Notebooks/model_top4.h5')
model_top9.save('/content/drive/My Drive/Colab Notebooks/model_top9.h5')
